### ISSUE TITLE
16:9 Aspect Ratio

### ISSUE THREAD

**Issue by lunatico67** [city96/ComfyUI_ExtraModels#100]
Hi
Of all the aspect ratios available in Sana is not 16:9, is there any way to get it?

**Comment by city96** [comment]
Doesn't seem like that's a res that's [used for training](https://github.com/NVlabs/Sana/blob/bcad148693affa4f6a971516b57e75d2ee0b3221/diffusion/data/datasets/utils.py#L175).

I guess 1.67 is the closest with 1280x768, which you could crop down to 1280x720 to get 16:9

**Comment by lunatico67** [comment]
thanks for your advice, that's what I'll do.
