### ISSUE TITLE
poor image quality

### ISSUE THREAD

**Issue by lunatico67** [city96/ComfyUI_ExtraModels#101]
It is not easy to start a successful project, let's hope that it will improve over time.
The quality of the images leaves much to be desired, it's terrible.
Humans and landscapes are not realistic at all, maybe it's good for anime, cartoon, comic... but for realistic pictures it's a disaster.
Its only advantages over other models is its superior speed and the variety of aspect ratios available.
A lot has to change to compete with models like Flux, Shuttle....
Can anyone show a positive and negative prompts that really work?

**Comment by shaun-ba** [comment]
I just came here to write the same thing, however if you check the "wrapper" which I think came before this repo, it looks great in the workflow attached?

https://github.com/zmwv823/ComfyUI-Sana/blob/main/workflow/Img_Gen-Sana-wf.png

**Comment by lunatico67** [comment]
Thanks shaum-ba, it is a beautiful image.
As I did it and it works for me (I do it with all custom nodes).
1- I never do it from ComfyUI Manager.
I go to the github of the custom node, in this example Sana: 
https://github.com/city96/ComfyUI_ExtraModels.git  (copy)
Go to  your custom nodes folder, in my case : C:\Users\Luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes
cmd and it will open your command prompt (windows).
git clone https://github.com/city96/ComfyUI_ExtraModels.git  (the custom node will be installed)
don't close the window, followed write cd..
again cd..  , you will reach C:\Users------\Documents\ComfyUI_windows_portable:
write:  python_embeded\python.exe -m pip install -r ComfyUI\custom_nodes\ComfyUI_ExtraModels\requirements.txt
and everything will install fine, at least it works for me.

**Comment by shaun-ba** [comment]
@lunatico67 I'm completely lost here. I shared a non-working workflow image with you, and suddenly you say it now works, but you reference this repo which that workflow isn't even using?

Would you be able to share your working workflow so I can replicate?

I am also using this repo in the custom nodes folder

**Comment by shaun-ba** [comment]
To be clear, I can generate images just fine before replying to your message. The reply was specifically related to poor image quality, my images are like cartoons, the faces are horrible and it's nothing like the image I shared above which is why I replied.
