### ISSUE TITLE
Error when executing PixArtCheckpointLoader

### ISSUE THREAD

**Issue by formulake** [city96/ComfyUI_ExtraModels#11]
I've loaded up the sample workflow and the models specified in the readme. I've redirected the nodes to the correct models and checked that they're loading. When I run the workflow, however, it spits out this error:

> Error occurred when executing PixArtCheckpointLoader:
> 
> PatchEmbed.__init__() got an unexpected keyword argument 'bias'
> 
> File "F:\Tools\ComfyUI\execution.py", line 155, in recursive_execute
> output_data, output_ui = get_output_data(obj, input_data_all)
> File "F:\Tools\ComfyUI\execution.py", line 85, in get_output_data
> return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
> File "F:\Tools\ComfyUI\execution.py", line 78, in map_node_over_list
> results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
> File "F:\Tools\ComfyUI\custom_nodes\ComfyUI_ExtraModels\PixArt\nodes.py", line 30, in load_checkpoint
> model = load_pixart(
> File "F:\Tools\ComfyUI\custom_nodes\ComfyUI_ExtraModels\PixArt\loader.py", line 51, in load_pixart
> model.diffusion_model = PixArtMS(**model_conf.unet_config)
> File "F:\Tools\ComfyUI\custom_nodes\ComfyUI_ExtraModels\PixArt\models\PixArtMS.py", line 110, in __init__
> super().__init__(
> File "F:\Tools\ComfyUI\custom_nodes\ComfyUI_ExtraModels\PixArt\models\PixArt.py", line 92, in __init__
> self.x_embedder = PatchEmbed(input_size, patch_size, in_channels, hidden_size, bias=True)

Could you let me know where I've gone wrong?

**Comment by city96** [comment]
What version of pytorch do you have? I've only tested it on 2.0/2.1 so far. (You can check by running `python -m pip show torch` inside your venv)

**Comment by formulake** [comment]
> What version of pytorch do you have? I've only tested it on 2.0/2.1 so far. (You can check by running `python -m pip show torch` inside your venv)

First I apologise for not seeing your reply sooner and thank you for responding. I've checked the torch version and it's version 2.1.1. Will that be a problem?
<img width="846" alt="image" src="https://github.com/city96/ComfyUI_ExtraModels/assets/7622615/1338e38f-1224-4ad3-bd49-00e1ce89b7d6">

**Comment by city96** [comment]
No that version should be fine. Maybe it's the `timm` package then? That one I only tested with version `0.6.13` so far, so you could try up/downgrading it to that version (i.e. `python -m pip install timm==0.6.13`)
