### ISSUE TITLE
Error occurred when executing T5v11Loader:  Using `low_cpu_mem_usage=True`

### ISSUE THREAD

**Issue by antipirin** [city96/ComfyUI_ExtraModels#17]
I've done all the installation's steps (including all updates), download all the necessary models (Pixart/T5/Vae), but I still have this:
```
Error occurred when executing T5v11Loader:

Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install accelerate`

File "D:\git\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\git\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\git\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\git\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ExtraModels\T5\nodes.py", line 57, in load_model
return (load_t5(
^^^^^^^^
File "D:\git\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ExtraModels\T5\loader.py", line 107, in load_t5
return EXM_T5v11(**model_args)
^^^^^^^^^^^^^^^^^^^^^^^
File "D:\git\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ExtraModels\T5\loader.py", line 44, in __init__
self.cond_stage_model = T5v11Model(
^^^^^^^^^^^
File "D:\git\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ExtraModels\T5\t5v11.py", line 38, in __init__
self.transformer = T5EncoderModel.from_pretrained(textmodel_path, **model_args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\git\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\modeling_utils.py", line 2970, 
in from_pretrained raise ImportError(
```
And I've also done this:
`python -m pip install bitsandbytes --prefer-binary --extra-index-url=https://jllllll.github.io/bitsandbytes-windows-webui`
And also upgraded the transformers.

I'm using Workflow example from repo.
My GPU: RTX 3080 10Gb
My OS: Win10
My nodes looks like this:

![image](https://github.com/city96/ComfyUI_ExtraModels/assets/114661071/3ceddd4c-85d7-49b9-a8b4-ca14f0682f77)

Can you help me to solve this problem?

**Comment by city96** [comment]
From the error message it looks like it also requires `accelerate` to load T5. See if installing it manually helps. I'll add it to the requirements.txt if it does.

```
python -m pip install accelerate
```

**Comment by antipirin** [comment]
> From the error message it looks like it also requires accelerate to load T5.

Yeah, this was the first thing that I've done (before open this Issue), but it didn't worked.
After all, I haven't add the directory's path to the Windows PATH in Environment Variables. Now, when I did it - PixArt started working.
I've done `~\ComfyUI_windows_portable\python_embeded>python.exe -m pip install accelerate` and added `~\ComfyUI_windows_portable\python_embeded\Scripts` to the PATH. It helps.
Sorry for bothering =)

**Comment by city96** [comment]
All good.

(BTW There's a small difference with running just `python -m pip` and using `python -s -m pip`. Not sure if the effect is the same but something to try if it comes up in the future!)
