### ISSUE TITLE
Today's Update broke your Node

### ISSUE THREAD

**Issue by Piscabo** [city96/ComfyUI_ExtraModels#18]
### ComfyUI Revision: 2111 [38ed2da2] | Released on '2024-04-05'

(IMPORT FAILED): ComfyUI\custom_nodes\ComfyUI_ExtraModels

ImportError: cannot import name 'get_models_from_cond' from 'comfy.sample' (H:\ComfyUI\comfy\sample.py)

Cannot import H:\ComfyUI\custom_nodes\ComfyUI_ExtraModels module for custom nodes: cannot import name 'get_models_from_cond' from 'comfy.sample' (H:\ComfyUI\comfy\sample.py)

**Comment by city96** [comment]
Thanks for the report. Looks like that bit's only for the reference sampler. I pushed a quick fix, lmk if anything else is broken.
