### ISSUE TITLE
Support for PixArt-Sigma

### ISSUE THREAD

**Issue by syddharth** [city96/ComfyUI_ExtraModels#19]
Pixart team uploaded the Pixart Sigma models:
[https://huggingface.co/PixArt-alpha/PixArt-Sigma](https://huggingface.co/PixArt-alpha/PixArt-Sigma)

**Comment by city96** [comment]
It should work now? Can you test it?

**Comment by specblades** [comment]
Looks like sampler is broken, i tested different dtype, cfg, samplers etc.
<img width="923" alt="image" src="https://github.com/city96/ComfyUI_ExtraModels/assets/165026436/782bcdb0-1587-4794-b48f-3b024bb67821">

**Comment by city96** [comment]
Looks like the 1024 one is out as well. No changes required other than the resolution by the looks of it.

Updated the readme/res select. Enjoy!
