### ISSUE TITLE
add t5 model with FP16 loader

### ISSUE THREAD

**Issue by l33tx0** [city96/ComfyUI_ExtraModels#2]

**Comment by city96** [comment]
Well *assuming* I didn't mess it up horribly, it should work now.

I added a dtype selector to the T5 loader node. You might have to re-add the node if it doesn't show up. Also moved the bnb load mode to there.

**Comment by drphero** [comment]
Is there even an FP16 version available? I tried to convert it myself, but I think I made a mistake along the way.

**Comment by drphero** [comment]
Alright, I've successfully converted the T5 model to fp16 and it works fine when the node is set to either auto or gpu and fp16. I've uploaded the model here: https://huggingface.co/theunlikely/t5-v1_1-xxl-fp16

**Comment by city96** [comment]
@drphero Nice job. I'll grab it to check if it's 1:1 with the original and then add it to the readme.

On that note, I have a bf16 one where I combined the two safetensor files into one that I use for debugging. I can upload it to HF if you (or anyone else) is interested.

**Comment by drphero** [comment]
> I can upload it to HF if you (or anyone else) is interested.

Certainly wouldn't hurt!

**Comment by city96** [comment]
@drphero [Here it is.](https://huggingface.co/city96/t5-v1_1-xxl-encoder-bf16/tree/main) I've tested and added both models to the readme. Thanks again!

(closing this as the FP16 loading has been added for a while now, and I'm really hoping I can switch to the official implementation once SD3 is released)
