### ISSUE TITLE
Clarification on docs multi GPU usage

### ISSUE THREAD

**Issue by diffustar** [city96/ComfyUI_ExtraModels#22]
The docs state the following but I cannot find any way to use it, any help or clarification?

    If you have a second GPU, selecting "cuda:1" as the device will allow you to use it for T5, freeing at least some VRAM/System RAM. Using FP16 as the dtype is recommended.

**Comment by city96** [comment]
Can you give me a bit more detail on what hardware you're running? Also, are you using `CUDA_VISIBLE_DEVICES` or the launch option `--cuda-device` somewhere? I think those cause the second GPU to not be visible.

Without them the other cuda device should be in the dropdown for the T5 loader.

![image](https://github.com/city96/ComfyUI_ExtraModels/assets/125218114/209e2e9c-5e09-4f55-abed-0ef3595bfea4)

**Comment by diffustar** [comment]
@city96 
I did use the ComfyUI launch parameter `--cuda-device 0` but I already removed it. I did forget about the `CUDA_VISIBLE_DEVICES`, after removing that one as well `cuda:1` did show up.

So it's solved now, thank you!

**Comment by diffustar** [comment]
Is it correct that the bnb4/bnb8 don't work on the cuda:1 selection? I'd say both gpu/cuda:1 should be allowed ?

![image](https://github.com/city96/ComfyUI_ExtraModels/assets/165323713/6c373884-ae51-4dd7-b8da-b3303c53519e)

**Comment by city96** [comment]
Oops, forgot about that. It should work now.

**Comment by diffustar** [comment]
> Oops, forgot about that. It should work now.

Awesome! Works now thanks again
