### ISSUE TITLE
Problem loading PixArt Sigma .safetensors + 2k support?

### ISSUE THREAD

**Issue by Mindspherical** [city96/ComfyUI_ExtraModels#24]
I seem to have issues loading the safetensors versions of PixArt Sigma as per below.

Separately, is the 2K model supported as yet?

<img width="864" alt="image" src="https://github.com/city96/ComfyUI_ExtraModels/assets/117719106/1a2b597c-c9f9-4c74-bbff-834d935c65f1">

**Comment by city96** [comment]
Did you update the node pack? It should work on latest and that error message seems off.

**Comment by Mindspherical** [comment]
Reinstalled the node. Working now, although the 2K Sigma model gives garbled output. I guess that's not yet supported?

Thanks!

**Comment by city96** [comment]
>I guess that's not yet supported?

There should be an option for it in both the model loader and the resolution selection dropdowns. PixArt seems to only work with the resolutions it was trained on.
