### ISSUE TITLE
requires Accelerate

### ISSUE THREAD

**Issue by YoannRb** [city96/ComfyUI_ExtraModels#28]
<img width="1284" alt="accelerate" src="https://github.com/city96/ComfyUI_ExtraModels/assets/168425291/2ffe78dd-d961-4ba9-8187-d18bc72ccece">

Hello, I'm trying to run the Abominable Spaghetti Workflow and I'm getting this error.
I installed every pips I saw on comfy ui's pages, and on this one, also installed the pip accelerate but I still have the error
I tried with both portable and classic comfy ui versions.
I tried with every dtype
8GB RTX 2080 with Ryzen 7 3800X and 64GB RAM

Hope you have the solution, thanks

**Comment by city96** [comment]
I could've sworn accelerate came as a default requirement for either transformers or comfyui, apparently not.

I've added it to the requirements file, so you can run the install command again and it should grab it.

```
.\python_embeded\python.exe -s -m pip install -r .\ComfyUI\custom_nodes\ComfyUI_ExtraModels\requirements.txt
```

**Comment by YoannRb** [comment]
And now it works like a charm !
thank you boss !
