### ISSUE TITLE
VAE error

### ISSUE THREAD

**Issue by Hellrunner2k** [city96/ComfyUI_ExtraModels#31]
i'm getting this one... also tried the other two.. same

![image](https://github.com/city96/ComfyUI_ExtraModels/assets/16692344/2e3dbb39-ca5e-4a60-953c-a903936c5c89)
ComfyUI: 2143 -27d580-(2024-04-23)

Error occurred when executing VAELoader:

'decoder.conv_in.weight'

File "D:\SD\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\SD\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\SD\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\SD\ComfyUI_windows_portable\ComfyUI\nodes.py", line 690, in load_vae
vae = comfy.sd.VAE(sd=sd)
^^^^^^^^^^^^^^^^^^^
File "D:\SD\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 222, in __init__
self.latent_channels = ddconfig['z_channels'] = sd["decoder.conv_in.weight"].shape[1]
~~^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by city96** [comment]
You can use the normal 1.5 / XL VAE for PixArt, or if you have an actual reason to use those special ones (testing/benchmarking/etc), then you can load them with the ExtraVAELoader node. See #29 

I've added a note about this in the readme now, hopefully clarifying it a bit.

**Comment by city96** [comment]
Well, happy it worked with Sigma. For Alpha, I'd recommend just using [this file](https://huggingface.co/stabilityai/sd-vae-ft-mse-original/blob/main/vae-ft-mse-840000-ema-pruned.safetensors) as mentioned in the other issue.

The ExtraVAELoader node looks different from the one in your images, and the error seems to be for the regular one. Still, there's some caveats like selecting the model type or the fact that the consistency decoder can't be used for encoding that could've caused your issues. I gave it a quick test and it seems to still work, though the VRAM requirements are too high for it to be useful.
Feel free to reopen with more info if you still run into issues!

![image](https://github.com/city96/ComfyUI_ExtraModels/assets/125218114/9ef34c51-20b1-4100-93c3-4c6dc7bd8be5)
