### ISSUE TITLE
PixArt: UNET conversion has missing keys!

### ISSUE THREAD

**Issue by Linaghan34** [city96/ComfyUI_ExtraModels#34]
settings in ComfyUI.
PixArt: UNET conversion has missing keys!
['y_embedder.y_embedding']
model_type EPS
Missing UNET keys ['pos_embed', 'y_embedder.y_embedding']
style: base
text_positive: stars, water, brilliantly, gorgeous large scale scene, a little girl, in the style of dreamy realism, light gold and amber, blue and pink, brilliantly illuminated in the background.
text_negative: anime, manga, illustration, cartoon, 3d, Photoshop, sketch, video game, draw, paint, cgi, canvas frame, watermark, signature, username, artist name
text_positive_styled: stars, water, brilliantly, gorgeous large scale scene, a little girl, in the style of dreamy realism, light gold and amber, blue and pink, brilliantly illuminated in the background.
text_negative_styled: anime, manga, illustration, cartoon, 3d, Photoshop, sketch, video game, draw, paint, cgi, canvas frame, watermark, signature, username, artist name
Loading T5 from 'J:\ComfyUI\models\t5'
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:50<00:00, 25.35s/it]
![image](https://github.com/city96/ComfyUI_ExtraModels/assets/127322778/cdeeb56d-5d74-4e99-8776-55dac55703b1)
And there is no option for pixartms sigma xl 2 512 in the model drop-down list.

**Comment by city96** [comment]
IIRC Sigma XL2 512 and 1024 share the same config, just the resolution is different. So they're both just called "PixArtMS_Sigma_XL_2"

As for the "missing keys" bit, that's expected with the diffusers weights, it should still work without that. What error are you running into?

**Comment by Linaghan34** [comment]
> IIRC Sigma XL2 512 and 1024 share the same config, just the resolution is different. So they're both just called "PixArtMS_Sigma_XL_2"
> 
> As for the "missing keys" bit, that's expected with the diffusers weights, it should still work without that. What error are you running into?

thanks,I was just wondering if that error reporting would affect the outgoing image, thanks for the answer, great plugin~!
