### ISSUE TITLE
[Feature Request] Support for HunyuanDiT

### ISSUE THREAD

**Issue by syddharth** [city96/ComfyUI_ExtraModels#35]
Here is the HF Repo: [https://huggingface.co/Tencent-Hunyuan/HunyuanDiT#using-gradio](https://huggingface.co/Tencent-Hunyuan/HunyuanDiT#using-gradio)

**Comment by aa2246740** [comment]
and Lumina T2I too~ looking forward

**Comment by city96** [comment]
Closing as HunYian DiT should be feature complete now. The issue for lumia is #56 for those that wish to follow it.
