### ISSUE TITLE
PixArt img2img

### ISSUE THREAD

**Issue by ardha27** [city96/ComfyUI_ExtraModels#4]
can we do img2img using PixArt?

**Comment by city96** [comment]
You asked at just the right time lol. If you pull the latest version you should be able to use the regular KSampler node with PixArt now. Can you test it?

![PixArtImg2Img](https://github.com/city96/ComfyUI_ExtraModels/assets/125218114/0a50b1d2-bd68-4c4f-a32e-2d87dfc06a16)

**Comment by ardha27** [comment]
yes, it works. but compare to DPM sampler, it looks like missing a bit of detail?
![image](https://github.com/city96/ComfyUI_ExtraModels/assets/48845217/7db5aceb-bcf6-4cba-86a8-661e4585d0a4)

**Comment by city96** [comment]
Interesting, could you provide more info about your environment?

- standalone/git clone?
- Comfy version? (latest?)
- torch version? (`pip show torch` inside venv)
- xformers? (`pip show xformers`)

I might have changed something I forgot about, let me try on a completely fresh install in the meantime.

**Comment by ardha27** [comment]
i use runpod comfyui
![image](https://github.com/city96/ComfyUI_ExtraModels/assets/48845217/c6c821bb-75a8-4219-b185-28c464713156)
![image](https://github.com/city96/ComfyUI_ExtraModels/assets/48845217/ec1faf85-e1b0-4b01-acec-f3a65db21bce)
![image](https://github.com/city96/ComfyUI_ExtraModels/assets/48845217/59402c2f-8728-4557-bac2-db3cf20149d3)

**Comment by ardha27** [comment]
i have another question. For current situation, is it able to add longer prompt to DPM Sampler?

**Comment by city96** [comment]
>i use runpod comfyui

Those versions seem fine, so I'm not sure what's causing the difference.

I assume you've tried different samplers/lower CFG with the KSampler node?

>For current situation, is it able to add longer prompt to DPM Sampler?

No, the DPM sampler is limited to the max length of the T5 encoder. I wanted to keep that 1:1 with the reference code to make sure I didn't break anything.

**Comment by ardha27** [comment]
> > i use runpod comfyui
> 
> Those versions seem fine, so I'm not sure what's causing the difference.
> 
> I assume you've tried different samplers/lower CFG with the KSampler node?
> 
> > For current situation, is it able to add longer prompt to DPM Sampler?
> 
> No, the DPM sampler is limited to the max length of the T5 encoder. I wanted to keep that 1:1 with the reference code to make sure I didn't break anything.

dpm_adaptive sampler is the closest one if i compare the result with pixart dpm sampler. but Ksampler need longer time to generate

**Comment by city96** [comment]
>dpm_adaptive sampler is the closest one if i compare the result with pixart dpm sampler.

That sounds about right.

>but Ksampler need longer time to generate

That part is normal too, I think. The reference pixart dpm one pads tokens so the negative/positive prompt are the same length, meaning the two passes get batched.

Padding T5 for the regular KSampler seems like a bad idea (which is the only thing I can think of to batch the two passes) though that is way above my paygrade...

**Comment by ardha27** [comment]
> > dpm_adaptive sampler is the closest one if i compare the result with pixart dpm sampler.
> 
> That sounds about right.
> 
> > but Ksampler need longer time to generate
> 
> That part is normal too, I think. The reference pixart dpm one pads tokens so the negative/positive prompt are the same length, meaning the two passes get batched.
> 
> Padding T5 for the regular KSampler seems like a bad idea (which is the only thing I can think of to batch the two passes) though that is way above my paygrade...

so that is the tradeoff for unlimited prompt length?

**Comment by city96** [comment]
>so that is the tradeoff for unlimited prompt length?

I guess so. Again, could just be that my implementation sucks lol. I'm sure there's a better way of doing it.

**Comment by ardha27** [comment]
Thanks

**Comment by ardha27** [comment]
Hi, i think they added code to change the max length of the T5

https://github.com/PixArt-alpha/PixArt-alpha/commit/dfa0b1bda67ce1f2b110af5ea973fa43eaaae5b0

**Comment by city96** [comment]
That's just changing the hardcoded value of 120 into an argument with a default value of 120 I think?

Like, the tokenizer can accept values longer than 120 and so can the actual PixArt model (like it does when used with the KSampler). The actual T5 model needs some extra stuff to make it work (you process it in segments of 120 then merge it into one, since it always wants an input that's 120 long as far as I understand it.)

The T5TextEncode node already has support for doing just that, and the KSampler can accept the longer outputs it produces.

![image](https://github.com/city96/ComfyUI_ExtraModels/assets/125218114/4adea78e-3dad-45ea-b38d-0a7a469d9755)

I don't want to hack that logic into the reference text encoder / sampler. Those are only there so I can verify that the outputs from the built-in KSampler/text encoder are (mostly) the same. Changing them would defeat the point of having them...
