### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! 

### ISSUE THREAD

**Issue by west5211** [city96/ComfyUI_ExtraModels#47]
Error reported when using HunYuan DiT:
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! 
It seems that both CPU and GPU are involved in the calculation at the same time?

**Comment by city96** [comment]
It should work now, reopen if the issue still persists.
