### ISSUE TITLE
Error occurred when executing HYDiTTextEncoderLoader:

### ISSUE THREAD

**Issue by EvanZouQ** [city96/ComfyUI_ExtraModels#49]
Error occurred when executing HYDiTTextEncoderLoader:

We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like Tencent-Hunyuan/HunyuanDiT is not the path to a directory containing a file named t2i/tokenizer\config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Can anyone help me? Many thanks.**

**Comment by city96** [comment]
Hello! I've added the required files to work without an internet connection, or when huggingface.co is unavailable. Please update to use!

**Comment by EvanZouQ** [comment]
> Hello! I've added the required files to work without an internet connection, or when huggingface.co is unavailable. Please update to use!

Many thanks.
