### ISSUE TITLE
T5v11Loader error

### ISSUE THREAD

**Issue by tetsuoo-online** [city96/ComfyUI_ExtraModels#5]
I'm really not good at those things, I checked the website indicated in the error message but where should I install that SentencePiece thing ? in the ExtraModel folder ? In a venv folder ? in ComfyUI/pythonembedded ? I tried in ComfyUI root but it was already there in my Python folders, so I'm completely lost again
![image](https://github.com/city96/ComfyUI_ExtraModels/assets/45845308/20539666-c908-40de-bb81-7ea82469ffc8)
![image](https://github.com/city96/ComfyUI_ExtraModels/assets/45845308/19251513-d971-4a55-a40d-a5259994a153)

**Comment by city96** [comment]
Hi!

You're in the right place with the command window, but your command is wrong. Could you try this one and report back?

```
.\python_embeded\python.exe -m pip install -r  .\ComfyUI\custom_nodes\ComfyUI_ExtraModels\requirements.txt
```

**Comment by tetsuoo-online** [comment]
Hi,
I doesn't look like it installed anything... I'm getting a list of "Requirement already satisfied" :

![image](https://github.com/city96/ComfyUI_ExtraModels/assets/45845308/8cffe870-7652-41f1-a0b2-337e152ecfb8)

The T5 tries to load itself, something happens, it idles at 50% then get stuck the same way as before.
Here a screenshot of the console if that can help :

![image](https://github.com/city96/ComfyUI_ExtraModels/assets/45845308/9b63e2d4-1a3b-41a9-a10a-9859d2e0ef61)

CPU or GPU do the same thing, CPU will only take longer to get stuck lol

**Comment by city96** [comment]
What about installing it with the `-s` flag like this? If it works I'll update the readme.

```
.\python_embeded\python.exe -s -m pip install -r  .\ComfyUI\custom_nodes\ComfyUI_ExtraModels\requirements.txt
```

**Comment by tetsuoo-online** [comment]
IT WORKED !! phew thanks x)

![image](https://github.com/city96/ComfyUI_ExtraModels/assets/45845308/8d8e6255-7293-4ee3-9194-c180b7c5eed7)

I can finally get the damn blue tank rofl will make more testing later x)
![image](https://github.com/city96/ComfyUI_ExtraModels/assets/45845308/e6bbd266-21d4-43f5-ac68-1b89bec8efe5)

**Comment by tetsuoo-online** [comment]
Actually I just made another 2 tests and my computer almost froze, it was using 20GB of RAM. That thing is as demanding as using Houdini x) (3D software)
So much for a failed attempt to make a pixelart anime character that the model obviously never heard of

![image](https://github.com/city96/ComfyUI_ExtraModels/assets/45845308/f026831a-30d2-42b4-aacf-adaefb4e3c3b)

**Comment by city96** [comment]
>Actually I just made another 2 tests and my computer almost froze, it was using 20GB of RAM (I have 32). That thing is as demanding as using Houdini x) (3D software)

I feel your pain, I'm also on 32GB RAM on my main desktop (though my 3D software of choice for torturing my poor computer is Blender). I might be able to get the RAM usage down if I implement the entire T5 model from scratch but that seems a bit overkill...

>So much for a failed attempt to make a pixelart anime character that the model obviously never heard of

I don't think PixArt had much anime in the training data, and the synthetic captions probably didn't include any character names. I'll try and do a full anime finetune of it eventually. Keyword being 'try'.

Anyway, I'll add that `-s` flag to the readme. Feel free to reopen/make another issue if sth breaks!

**Comment by tetsuoo-online** [comment]
> Anyway, I'll add that `-s` flag to the readme. Feel free to reopen/make another issue if sth breaks!

-s ? sth ? wut lol I have no idea what you're talking about, Python jargon is tough I see xDD
