### ISSUE TITLE
Can only generate images with a size of 1024x1024.

### ISSUE THREAD

**Issue by hexi2024hexi** [city96/ComfyUI_ExtraModels#51]
测试了一下，只能生成1024x1024的图片，其规格的图片比如1024x768，或者768x1024的图片，

**Comment by EvanZouQ** [comment]
> 测试了一下，只能生成1024x1024的图片，其规格的图片比如1024x768，或者768x1024的图片，

Error occurred when executing HYDiTTextEncoderLoader:

We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like Tencent-Hunyuan/HunyuanDiT is not the path to a directory containing a file named t2i/tokenizer\config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'

亲，你有碰到这个问题吗？怎么解决的？谢谢啦

**Comment by city96** [comment]
@hexi2024hexi @EvanZouQ  I have pushed a fix to both issues. Please update and try again!
