### ISSUE TITLE
In hunyuan, can now generate 1280x768, but it's cropped

### ISSUE THREAD

**Issue by festivus37** [city96/ComfyUI_ExtraModels#54]
Hi, thanks for your great work integrating what chaojie started with these hunyuan nodes. I've been using theirs until I just saw that you updated yours.  You can now generate in 1280x768, but it's just cropped 1024x1024. If you look at the difference between theirs and yours, they've got a node that specifies a resolution on the checkpoint loader as well.  You need the resolution in both the empty latent AND the checkpoint loader so that it doesn't just still do 1024x1024 and crops the image. An example prompt that will cut off the head if not done correctly at 1280x768 is the following. Thanks very much for your work on this. The prompt: Anime-style illustration featuring a muscular cyborg character with glowing eyes, mechanical arms and tubes, highlighted in fiery orange and contrasting deep shadows, standing powerfully with large machinery in the background, sharp lines, and dynamic shading enhancing the intensity and futuristic atmosphere.

**Comment by city96** [comment]
Thank you very much for the report. I've tracked down the issue and have fixed it (I think).

There is a "HYDiTSrcSizeCond" node that can be used to replicate the original "cropped" behavior as well, but it is **not required** for normal usage.

Could you please test it again?

**Comment by festivus37** [comment]
Hi, unfortunately it's still cropped. I uninstalled anything I had previous and did a git clone of the repo url. doing a git pull inside the dir says already up to date (just making sure I have the latest files.  I'm attaching a screenshot.
![Screenshot 2024-05-27 at 11 20 11 PM](https://github.com/city96/ComfyUI_ExtraModels/assets/170977426/660f36cb-4bf9-4c11-980f-d212fda3d5c0)

**Comment by city96** [comment]
Wait, I'm stupid, I had the width/height the wrong way around which is why it seemed "cropped". Now it really should be 1:1 to the original if you update. Hopefully.

![image](https://github.com/city96/ComfyUI_ExtraModels/assets/125218114/1e4e330c-d637-43f3-a557-01408c0f415c)

**Comment by festivus37** [comment]
![image](https://github.com/city96/ComfyUI_ExtraModels/assets/170977426/7f05e5a6-0b64-48bd-88c7-c7cb5a095954)
Yep, we're in good shape now. Thanks again for getting this worked out.

**Comment by city96** [comment]
No problem, sorry for missing the real issue the first time around lol
