### ISSUE TITLE
`/models/T5` should be `/models/t5`

### ISSUE THREAD

**Issue by liusida** [city96/ComfyUI_ExtraModels#55]
in the README.md, you mentioned:
```
Download the [second text encoder from here](https://huggingface.co/Tencent-Hunyuan/HunyuanDiT/blob/main/t2i/mt5/pytorch_model.bin) and place it in ComfyUI/models/T5 - rename it to "mT5.bin"
```
But when i install that on Linux, the node is looking for the `ComfyUI/models/t5` folder. So i think `T` should be lower case.

Thanks.

**Comment by city96** [comment]
You're right, it's lowercase everywhere else, even in the code where the folder creation happens. Updated the readme to reflect this.

I've also added a link to a decoder-only fp16 safetensor version of mT5-xl that I converted, which should be smaller/load faster compared to the pytorch model.
