### ISSUE TITLE
Issues trying to run T5v1.1 Loader

### ISSUE THREAD

**Issue by VGF64** [city96/ComfyUI_ExtraModels#59]
I'm trying to run on PixArt Sigma but this node kept giving me trouble every time. I had uninstalled and reinstalled the node to no avail. I have the necessary requirements to run PixArt Sigma in the t5 folder but when the path is set to "folder" it kept giving me various kinds of errors, such as "missing config.json". The config name was initially renamed to something different so I renamed it back, and then it gave me another error saying: 

![Screenshot (367)](https://github.com/city96/ComfyUI_ExtraModels/assets/126835875/d1a3a9d0-924b-4613-b76f-205854ec5e05)

And this is where the heart of the confusions lie. I have seen other people's workflow with the path option set to "folder" and they work just fine. This issue seems to be entirely unique to me as I don't see anyone else with this problem.

Also to note, when the path type is set to "file", the output image becomes a noisy mess, and even that is in question because I'm still not entirely sure what causes that too. I got the right VAE for it too.

![Screenshot (364)](https://github.com/city96/ComfyUI_ExtraModels/assets/126835875/40ad2c45-21aa-43cc-9bce-7435c4f599d0)

**Comment by VGF64** [comment]
I got it resolved! I followed this specific guide and it did the trick! I think me not having xformers was the reason it wasn't working. Or I didn't have the correct materials to run PixArt Sigma.

https://civitai.com/articles/5355/installing-comfyui-for-use-with-pixart-sigma

**Comment by city96** [comment]
I think for the original issue, it must've been a filename problem. It's loaded via transformers so it just looks for very specific files and filenames. Maybe you were missing the model index json. Relevant part of error is this:

![image](https://github.com/city96/ComfyUI_ExtraModels/assets/125218114/193c1c5f-0c7d-437f-bf60-9a7ab8aa4804)


For loading it as a file, the reason it didn't work was that it only loaded one half of the model (there's 2 parts, hence why we need to use the "folder" mode). There's one linked in the readme that should work with that but yeah, sorry, it's more convoluted than it should be. Glad you got it working.
