### ISSUE TITLE
Hunyuan 1.0 is bad, replace with 1.1 due to oversaturation issues.

### ISSUE THREAD

**Issue by DarkAlchy** [city96/ComfyUI_ExtraModels#66]
As the title says.

**Comment by festivus37** [comment]
1.1 works for me with the existing nodes, same with 1.1 distilled.

**Comment by DarkAlchy** [comment]
I moved on from Hunyuan as I have with any dit based models.  After what LyCORIS informed me, I am done with them as they can never come half the speed close to a unet/clip scheme on my 4090.
