### ISSUE TITLE
Can't load pixart model in current version of comfy, pixart\loader.py throws error

### ISSUE THREAD

**Issue by DanPli** [city96/ComfyUI_ExtraModels#80]
Comfy complains about the model patcher using an unexpected keyword argument current_device .

I fixed it for me by doing this:

In pixart\loader.py Line 114 find this: 
`

	model_patcher = comfy.model_patcher.ModelPatcher(
		model,
		load_device = load_device,
		offload_device = offload_device,
		current_device = "cpu",
	)
`
remove

`,
		current_device = "cpu",
`

So that it reads 

```

	model_patcher = comfy.model_patcher.ModelPatcher(
		model,
		load_device = load_device,
		offload_device = offload_device
	)

```

**Comment by city96** [comment]
Thanks, should be fixed.
