### ISSUE TITLE
Support T5 xxl gguf

### ISSUE THREAD

**Issue by ReyJ94** [city96/ComfyUI_ExtraModels#81]
I have been using T5 xxl q5_k_m for flux. I tried to load it with the default gguf clip loader but it did not work. The clip loader works for pixart sigma T5 non gguf. The gguf version is so much faster and it would be nice to have it. Can you support it in extra models nodes ?

**Comment by city96** [comment]
Fixed in GGUF repo, see https://github.com/city96/ComfyUI-GGUF/issues/52
