### ISSUE TITLE
[SANA] Add support for the other VAE weights format

### ISSUE THREAD

**Issue by frutiemax92** [city96/ComfyUI_ExtraModels#91]
I'd like to try this VAE with SANA but it is currently incompatible with the weight names.
https://huggingface.co/mit-han-lab/dc-ae-f32c32-mix-1.0-diffusers/tree/main

It would be great to detect the format of the weights and rename/remap the weights.

**Comment by city96** [comment]
This recently merged PR should satisfy this requirement: https://github.com/city96/ComfyUI_ExtraModels/pull/103
