### ISSUE TITLE
Sana - not work - grey image

### ISSUE THREAD

**Issue by Aljnk** [city96/ComfyUI_ExtraModels#93]
![workflow](https://github.com/user-attachments/assets/31604ca9-e33a-4992-8f2a-b59bbf06f8b8)

**Comment by merecesarchviz** [comment]
me get yellow empty image!!

**Comment by syllebra** [comment]
And black for me...

**Comment by city96** [comment]
I'm doing a full rewrite of most of the code here, though unsure if it fixes it. It's not really ready for testing yet https://github.com/city96/ComfyUI_ExtraModels/pull/92

From the screenshot my only real guess would be some issue with either package versions (upgrading transformers for the tenc might help) or maybe an issue with running it on cuda (leaving it on CPU/auto should be fine, Gemma 2B is fast enough)

**Comment by sintetico82** [comment]
When it finishes, it looks like there is this error:

ComfyUI\nodes.py:1534: RuntimeWarning: invalid value encountered in cast  
img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))

**Comment by merecesarchviz** [comment]
> I'm doing a full rewrite of most of the code here, though unsure if it fixes it. It's not really ready for testing yet #92
> 
> From the screenshot my only real guess would be some issue with either package versions (upgrading transformers for the tenc might help) or maybe an issue with running it on cuda (leaving it on CPU/auto should be fine, Gemma 2B is fast enough)

I try already cuda or cpu i got the same black image or gray image as result! i have a rtx 4090

**Comment by guennibear** [comment]
Same problem here... also on a 4090 only grey image

**Comment by Hymaera** [comment]
GUYS, I found the solution for black/grey/output!

Uninstall Extra Models for ComfyUI.

Restart ComfyUI.

Go to Install Missing Custom Nodes:

Click Install gemma...
BUT for Extra Models for ComfyUI, click Install via Git URL and add:

https://github.com/Efficient-Large-Model/ComfyUI_ExtraModels

Restart again and hit Queue. It will download the correct models automatically.

And DONE!

All the love!

**Comment by guennibear** [comment]
Hymaera's fix worked for me too

**Comment by sintetico82** [comment]
Ok! It works also form me, but i had to put this node like this:

![image](https://github.com/user-attachments/assets/90e15a07-280d-4bfc-be7a-bd3af6568b88)

Looks like he want download the VAE and not let chose the alredy existing on your directory

**Comment by DavidAllenNeron** [comment]
> GUYS, I found the solution for black/grey/output!
> 
> Uninstall Extra Models for ComfyUI.
> 
> Restart ComfyUI.
> 
> Go to Install Missing Custom Nodes:
> 
> Click Install gemma... BUT for Extra Models for ComfyUI, click Install via Git URL and add:
> 
> https://github.com/Efficient-Large-Model/ComfyUI_ExtraModels
> 
> Restart again and hit Queue. It will download the correct models automatically.
> 
> And DONE!
> 
> All the love!

ComfyUI Desktop won't let me Install via Git URL, I click it and nothing happens :(

**Comment by sintetico82** [comment]
@DavidAllenNeron, please check if you have received a message about security restrictions from ComfyUI. In my case, I had to add "security_level = weak" in the following file: custom_nodes\ComfyUI-Manager\config.ini

**Comment by merecesarchviz** [comment]
> GUYS, I found the solution for black/grey/output!
> 
> Uninstall Extra Models for ComfyUI.
> 
> Restart ComfyUI.
> 
> Go to Install Missing Custom Nodes:
> 
> Click Install gemma... BUT for Extra Models for ComfyUI, click Install via Git URL and add:
> 
> https://github.com/Efficient-Large-Model/ComfyUI_ExtraModels
> 
> Restart again and hit Queue. It will download the correct models automatically.
> 
> And DONE!
> 
> All the love!

following his fix, work perfect now all is working well! thank you mate

**Comment by smithian123** [comment]
Which models do you delete? I deleted the vae and it doesn't auto-download it again.

**Comment by hugobitola** [comment]
> GUYS, I found the solution for black/grey/output!
> 
> Uninstall Extra Models for ComfyUI.
> 
> Restart ComfyUI.
> 
> Go to Install Missing Custom Nodes:
> 
> Click Install gemma... BUT for Extra Models for ComfyUI, click Install via Git URL and add:
> 
> https://github.com/Efficient-Large-Model/ComfyUI_ExtraModels
> 
> Restart again and hit Queue. It will download the correct models automatically.
> 
> And DONE!
> 
> All the love!

This worked fine!! Thanks!!

**Comment by city96** [comment]
Added a note to the readme that links out to their readme/fork for the time being.

![image](https://github.com/user-attachments/assets/f3b65a30-2204-458a-bda8-f87631c520d3)

**Comment by aignescarrey** [comment]
WOW working ! THX :)

**Comment by DavidAllenNeron** [comment]
> @DavidAllenNeron, please check if you have received a message about security restrictions from ComfyUI. In my case, I had to add "security_level = weak" in the following file: custom_nodes\ComfyUI-Manager\config.ini

I did that but it still won't do anything.. I click the button and nothing happens.

I'm getting this in the console (devtools): 9
comfyui-manager.js:762 Uncaught 
Error: prompt() is and will not be supported.
    at HTMLButtonElement.onclick (comfyui-manager.js:762:17)
comfyui-manager.js:762 Uncaught 
Error: prompt() is and will not be supported.
    at HTMLButtonElement.onclick (comfyui-manager.js:762:17)

**Comment by ermanitu** [comment]
Thank you, Hymaera, installing from repo and the problem was solved.

**Comment by Minimidget007-WE** [comment]
After doing @Hymaera method ive been getting this error
 ExtraVAELoader
No module named 'diffusers'
![image](https://github.com/user-attachments/assets/f3355377-a6fe-452b-bffe-da28e7757bd9)

**Comment by tolotratlt** [comment]
> After doing @Hymaera method ive been getting this error ExtraVAELoader No module named 'diffusers' ![image](https://private-user-images.githubusercontent.com/83983620/398723827-f3355377-a6fe-452b-bffe-da28e7757bd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5OTgxMjcsIm5iZiI6MTczNTk5NzgyNywicGF0aCI6Ii84Mzk4MzYyMC8zOTg3MjM4MjctZjMzNTUzNzctYTZmZS00NTJiLWJmZmUtZGEyOGU3NzU3YmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDEzMzcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZTQzNTM1MTI2NGZjNDFiMGNjNjQ5NDA4OWY2OGEyMTAyYmEyYjYzMjM5YWU1OWE0NzFhMTY0NjQ0ZmFiOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gK09wp16d-hlqouvqgy0Wf8K__FC5zbH02z-V6UBiiU)

I had the same issue. 
Doing 
`pip install git+https://github.com/huggingface/diffusers`
solved my ExtraVAELoader issue

**Comment by JohnKostly** [comment]
@DavidAllenNeron Having same problem as you.

Apparentlly the directory for the config changed in version 3.
The new directory for the config.ini is 
`ComfyUI\user\default\ComfyUI-Manager`

**Comment by Ottokar-silly** [comment]
YES! Many thanks for your guide.

**Comment by HeinzZysset** [comment]
I've made some progress. But now I'm having problems with KSampler.

RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.HalfTensor) should be the same

How can i fix this problem? Please help

**Comment by HeinzZysset** [comment]
> [@DavidAllenNeron](https://github.com/DavidAllenNeron), please check if you have received a message about security restrictions from ComfyUI. In my case, I had to add "security_level = weak" in the following file: custom_nodes\ComfyUI-Manager\config.ini

Thanks for the Hint. Where can i see the Parameters and Interpretation for the entry's in this config.ini?
