### ISSUE TITLE
Sana node not working

### ISSUE THREAD

**Issue by talon468** [city96/ComfyUI_ExtraModels#95]
File "F:\ComfyUI\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\ComfyUI\\ComfyUI\\custom_nodes\\Sana\\__init__.py'

Cannot import F:\ComfyUI\ComfyUI\custom_nodes\Sana module for custom nodes: [Errno 2] No such file or directory: 'F:\\ComfyUI\\ComfyUI\\custom_nodes\\Sana\\__init__.py'

**Comment by city96** [comment]
It looks like you copied the Sana folder, the rest of the repository is required for the models to load correctly, the folders are not standalone custom nodes.

Please clone or copy the entire `ComfyUI_ExtraModels` folder to your `ComfyUI\custom_nodes` folder.

**Comment by talon468** [comment]
No I installed the extra models from comfyui first the cloned the sana
repository

**Comment by city96** [comment]
If you mean the original Sana repository from [here](https://github.com/NVlabs/Sana) - that one isn't required.

**Comment by talon468** [comment]
Ok, thanks for the clarification.
