### ISSUE TITLE
Gemma model download fix.

### ISSUE THREAD

**Issue by freyandere** [city96/ComfyUI_ExtraModels#96]
Gemma model download fix, as Gemma is a gated model.
Needs a token lib added in nodes.py (custom_nodes\ComfyUI_ExtraModels\Gemma) -  huggingface_hub.errors.GatedRepoError

import os
import torch
import folder_paths
from transformers import AutoTokenizer, AutoModelForCausalLM
from ..utils.dtype import string_to_dtype
from huggingface_hub import login ##my edit
from huggingface_hub import snapshot_download
login(token = 'hf_token') ##my edit

**Comment by city96** [comment]
Adding the token like that seems like a bad idea - i.e. if we make it exposable via an input field in a custom node, then people would 100% end up sharing their tokens together with their workflows/debug logs.

You should be able to use `huggingface-cli login` on the console to allow all hf libraries to access gated models, which is the preferred way.

**Comment by freyandere** [comment]
Appreciate the response and small education, will know for the future.
Thank you.
