### ISSUE TITLE
Sana ... Error: importlib.metadata.PackageNotFoundError: No package metadata was found for bitsandbytes

### ISSUE THREAD

**Issue by fbauer-kunbus** [city96/ComfyUI_ExtraModels#97]
Like many others, when I try to use Sana I get the familiar error on my Win-11 PC:

**importlib.metadata.PackageNotFoundError: No package metadata was found for bitsandbytes**

after following this video: https://www.youtube.com/watch?v=gxFRxwkwXnY

Looks like the creator of the video is on another system (maybe Linux) - since his ComfyUI manager had slightly different background. So it may be due to missing windows dependencies. This should be addressed here!

**Comment by city96** [comment]
Added it to the requirements temporarily https://github.com/city96/ComfyUI_ExtraModels/commit/aec37b0ce7f3debed4aaab8d20398646331de219

You can install it via `python_embeded\python.exe -s -m pip install bitsandbytes` if you don't want to rerun the install command via the manager.

**Comment by fbauer-kunbus** [comment]
> You can install it via `python_embeded\python.exe -s -m pip install bitsandbytes` if you don't want to rerun the install command via the manager.

I uninstalled the ExtraModels, stopped the ComfyUI and restarted it - and now the 'Manager' is missing again, so I cannot re-install the ExtraModels. This sh*t with the 'Manager' is so annoying - I am on the verge of quitting ComfyUI alltogether.

**Comment by fbauer-kunbus** [comment]
Sorry for becoming annoyed - but ComfyUI is such a JENGA tower, where you almost expect that something is broken after each update.
I now installed everything and re-created the workflow like shown in this video:
https://www.youtube.com/watch?v=gxFRxwkwXnY

But like many other users (see comments there) I only get a black image as output - and massive error messages with 'Missing VAE keys'

**Comment by fbauer-kunbus** [comment]
Tried all of those files - none of them works. Even if the 'bitsandbytes' error message is no longer appearing, the 'Missing VAE keys' error persists - and you won't get any other output that black or blue or gray rectangle. 
This whole Sana thing in ComfyUI has not been tested seriously and works only under very special conditions - which nobody even seems to admit.
