### ISSUE TITLE
401 Client Error. (Request ID: Root=1-67545d8b33-604123b6654831703760a42c;a38b7bcf-24dc-4b79-bc8b-eb68f613c5b2)  Cannot access gated repo for url https://huggingface.co/google/gemma-2-2b-it/resolve/299a8560bedf22ed1c72a8a11e7dce4a7f9f51f8/.gitattributes. Access to model google/gemma-2-2b-it is restricted. You must have access to it and be authenticated to access it. Please log in.

### ISSUE THREAD

**Issue by jonnytracker** [city96/ComfyUI_ExtraModels#99]
401 Client Error. (Request ID: Root=1-6545d8b33-604123b6654831703760a42c;a38b7bcf-24dc-4b79-bc8b-eb68f613c5b2)

Cannot access gated repo for url https://huggingface.co/google/gemma-2-2b-it/resolve/299a8560bedf22ed1c72a8a11e7dce4a7f9f51f8/.gitattributes.
Access to model google/gemma-2-2b-it is restricted. You must have access to it and be authenticated to access it. Please log in.

**Comment by city96** [comment]
Either log in via `huggingface-cli login` or select the other item in the dropdown, which isn't gated ("Efficient-Large-Model/gemma-2-2b-it").
